repos:
  - repo: https://github.com/mrsimonemms/pre-commit-hooks
    rev: v1.2.0
    hooks:
      - id: license-eye
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: pretty-format-json
        args:
          - --autofix
          - --no-sort-keys
      - id: check-json
      - id: check-yaml
        args:
          - --allow-multiple-documents
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.2.0
    hooks:
      - id: conventional-pre-commit
        stages:
          - commit-msg
  - repo: https://github.com/trussworks/pre-commit-hooks
    rev: v1.1.1
    hooks:
      - id: markdown-toc
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.13.0
    hooks:
      - id: markdownlint-cli2
  - repo: https://github.com/mrsimonemms/toodaloo
    rev: v0.2.2
    hooks:
      - id: scan
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: v0.18.0
    hooks:
      - id: terraform-docs-go
        args:
          - markdown
          - .
          - --hide-empty
          - --recursive-include-main=true
          - --output-file=README.md
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: "v1.91.0"
    hooks:
      - id: terraform_fmt
        args:
          - --args=-recursive
      - id: terragrunt_fmt
        args:
          - --args=-recursive
      - id: terraform_tflint
      - id: terraform_trivy
      - id: terraform_validate
        exclude: ^stacks
      - id: terragrunt_validate
        files: ^stacks/(\w+)/(\w+)/.*
